version: '3'

services:

  iprwc-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=iprwc
      - MYSQL_USER=iprwc
      - MYSQL_PASSWORD=admin
    volumes:
      - iprwc-mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

  iprwc-api:
    build: .
    restart: on-failure
    env_file: .env
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - ADMIN_USERNAME
      - ADMIN_HASHED_PASSWORD
      - JWT_COOKIE_NAME
      - JWT_LIFETIME
      - JWT_SECRET
      - JWT_COOKIE_SECURE
      - JWT_COOKIE_RESTRICT_SITE
      - CORS_ALLOWED_ORIGINS
    depends_on:
      - iprwc-mysql
    volumes:
      - ./data:/data
    ports:
      - 8080:8080

volumes:
  iprwc-mysql-volume:
